### PR TITLE
feat: set codesign identity

### PR DESCRIPTION
**Pull request by hrueger**
Hi all,
thanks for this excellent package, I'm using it quite often.

This adds support for providing the macos codesign identity via a new `--codesign-identity` cli argument.

If there's anything which needs to be added / fixed, just tell me.

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]

**Comment by hrueger** [comment]
Hm, I don't know why some of the tests fail... maybe just flaky CI?

**Comment by robertsLando** [comment]
>  maybe just flaky CI?

Yeah can ignore them if are not marked as required

**Comment by hrueger** [comment]
Is there anything else to be done? @jesec

**Comment by Mikescops** [comment]
Hello, you should write a test scenario for this new option.

For instance you can get inspiration here: https://github.com/vercel/pkg/blob/main/test/test-50-no-signature/main.js
and use the stdout of the codesign `--verify` command to check if the identity you used as an input is the correct one used.

**Comment by hrueger** [comment]
Hi @Mikescops,
thanks for the response. I'm currently very busy and therefore can't work on it right now. If someone wants to take it from here, feel free, otherwise I'll get to it in probably more like three months or so.

**Comment by gabrieldonadel** [comment]
Is there something I can help with to get this PR merged?

**Comment by hrueger** [comment]
Hi @gabrieldonadel,
I believe the only thing missing is tests. I'm, however, not very familiar with writing tests and I don't have lots of time currently, so if you want to write some and finish this up, that would be great!

**Comment by robertsLando** [comment]
Can someone resolve conflicts?

**Comment by gabrieldonadel** [comment]
don't close it 🙏

**Comment by robertsLando** [comment]
For anyone that is interested in this project, giving that I don't receive any feedback from Vercel anymore, I created my own forks of both pkg and pkg-fetch:

[yao-pkg/pkg-fetch](https://github.com/yao-pkg/pkg-fetch)
[yao-pkg/pkg](https://github.com/yao-pkg/pkg)

If someone is interested in helping me create a PR or move your active PR to those repositories.

Thanks 🙏🏼

**Pull request closed without merging**
