### PR TITLE
Added support for async generators

### PR DESCRIPTION
**Pull request by leo**
We need this to make [this](https://github.com/zeit/now-cli/pull/1710) work by adding support for async generators.

### CODE REVIEW

**Comment by leo** [comment]
As seen in https://github.com/zeit/now-cli/pull/1710, it fixes our problem (I published `pkg@4.3.4-canary.1` in order to test it out).

**Comment by timneutkens** [comment]
Can we add a regression test for this?

**Comment by timneutkens** [comment]
As per talking with @leo:

Node.js supports generator syntax:

```
function* a() {
  yield 1;
}
```

But it doesn't support `async` generator syntax:

```
async function* a() {
  yield 1;
}
```

**Comment by leo** [comment]
Closing in favor of https://github.com/zeit/now-cli/pull/1710/commits/158f96287ebdc7fd5cf0671ca451e0649c96b5de

**Pull request closed without merging**
