### PR TITLE
Show version before compilation

### LINKED ISSUE #36: Show pkg version before compilation

### PR DESCRIPTION
**Pull request by martinstarman**
My attempt to close #36.

### CODE REVIEW

**Comment by igorklopov** [comment]
Oh, it will not show version when targets are specified. Also ```log.info(`pkg@${version}`);```

**Comment by martinstarman** [comment]
Oh, sorry. I was fixing lint issues and ends with old version.

**Comment by igorklopov** [comment]
You know, let's place that log.info right after your '-v' handler. This way we have version logging parts close to each other.

**Comment by martinstarman** [comment]
Done!

**Pull request merged**
