### PR TITLE
dictionary: bunyan

### PR DESCRIPTION
**Pull request by weirongxu**
fix bunyan dynamic require

### CODE REVIEW

**Comment by igorklopov** [comment]
Is it only to remove a warnings? Does it break at run time?
Try as `require('mv', 'may-exclude');`

**Comment by weirongxu** [comment]
@igorklopov Its break at run time when use `rotating-file` steam.
```js
const logger = require('bunyan').createLogger({
  name: 'pkg',
  streams: [{
    type: 'rotating-file',
    path: 'pkg.log',
    level: 'info',
  }]
})
```

**Comment by weirongxu** [comment]
@igorklopov I try to add `require('mv', 'may-exclude')`, Its work very well.

**Comment by igorklopov** [comment]
`require('mv', 'may-exclude');` still absent in changes. Add it please

**Comment by igorklopov** [comment]
Oh, sorry, now i get the problem. Please undo `may-exclude`. It is not needed really. And then i merge 👍

**Pull request merged**
